import { RecipeData } from './types';

export const MOCK_RECIPE: RecipeData = {
  id: '1',
  title: 'Spaghetti Bolognese',
  category: 'Main Course',
  area: 'Italian',
  instructions: 'Cook pasta. Prepare sauce. Combine and serve.',
  tags: ['Pasta', 'Italian', 'Main Course'],
  imageUrl: 'https://www.themealdb.com/images/media/meals/5fu4ew1760524857.jpg',
  youtubeUrl: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
  ingredients: [
    { ingredient: 'Spaghetti', measure: '200g' },
    { ingredient: 'Ground Beef', measure: '150g' },
    { ingredient: 'Tomato Sauce', measure: '100ml' },
    { ingredient: 'Onion', measure: '1 medium' },
    { ingredient: 'Garlic', measure: '2 cloves' },
    { ingredient: 'Olive Oil', measure: '2 tbsp' },
    { ingredient: 'Salt', measure: 'to taste' },
    { ingredient: 'Pepper', measure: 'to taste' },
  ],
  dateModified: '2024-01-01',
};

export const MOCK_RECIPE_LIST: RecipeData[] = [
  MOCK_RECIPE,
  {
    id: '2',
    title: 'Chicken Curry',
    category: 'Main Course',
    area: 'Indian',
    instructions: 'Cook chicken. Prepare curry sauce. Combine and serve with rice.',
    tags: ['Curry', 'Indian', 'Main Course'],
    imageUrl: 'https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=V1bFr2SWP1I',
    ingredients: [
      { ingredient: 'Chicken', measure: '200g' },
      { ingredient: 'Curry Powder', measure: '2 tbsp' },
      { ingredient: 'Coconut Milk', measure: '150ml' },
      { ingredient: 'Onion', measure: '1 medium' },
      { ingredient: 'Garlic', measure: '2 cloves' },
      { ingredient: 'Ginger', measure: '1 inch' },
      { ingredient: 'Oil', measure: '2 tbsp' },
      { ingredient: 'Salt', measure: 'to taste' },
      { ingredient: 'Pepper', measure: 'to taste' },
    ],
    dateModified: '2024-02-15',
  },
  {
    id: '3',
    title: 'Caesar Salad',
    category: 'Salad',
    area: 'American',
    instructions: 'Prepare dressing. Toss lettuce with dressing, croutons, and cheese.',
    tags: ['Salad', 'Healthy', 'Appetizer'],
    imageUrl: 'https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=Y8Tko2YC5hA',
    ingredients: [
      { ingredient: 'Romaine Lettuce', measure: '1 head' },
      { ingredient: 'Croutons', measure: '100g' },
      { ingredient: 'Parmesan Cheese', measure: '50g' },
      { ingredient: 'Caesar Dressing', measure: '100ml' },
      { ingredient: 'Lemon Juice', measure: '1 tbsp' },
      { ingredient: 'Olive Oil', measure: '2 tbsp' },
      { ingredient: 'Salt', measure: 'to taste' },
      { ingredient: 'Pepper', measure: 'to taste' },
    ],
    dateModified: '2024-03-10',
  },
  {
    id: '4',
    title: 'Pancakes',
    category: 'Breakfast',
    area: 'American',
    instructions: 'Mix ingredients. Cook on griddle until golden brown. Serve with syrup.',
    tags: ['Breakfast', 'Sweet', 'Easy'],
    imageUrl: 'https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=1APZ6bX8q0g',
    ingredients: [
      { ingredient: 'Flour', measure: '200g' },
      { ingredient: 'Milk', measure: '250ml' },
      { ingredient: 'Eggs', measure: '2' },
      { ingredient: 'Sugar', measure: '2 tbsp' },
      { ingredient: 'Baking Powder', measure: '1 tsp' },
      { ingredient: 'Salt', measure: 'a pinch' },
      { ingredient: 'Butter', measure: 'for cooking' },
    ],
    dateModified: '2024-04-05',
  },
  {
    id: '5',
    title: 'Cauliflower Soup',
    category: 'Soup',
    area: 'French',
    instructions: 'Cook cauliflower. Blend with broth and cream. Season and serve hot.',
    tags: ['Soup', 'Vegetarian', 'Appetizer'],
    imageUrl: 'https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=3AAdKl1UYZs',
    ingredients: [
      { ingredient: 'Cauliflower', measure: '1 head' },
      { ingredient: 'Vegetable Broth', measure: '500ml' },
      { ingredient: 'Cream', measure: '100ml' },
      { ingredient: 'Onion', measure: '1 medium' },
      { ingredient: 'Garlic', measure: '2 cloves' },
      { ingredient: 'Butter', measure: '2 tbsp' },
      { ingredient: 'Salt', measure: 'to taste' },
      { ingredient: 'Pepper', measure: 'to taste' },
    ],
    dateModified: '2024-05-20',
  },
  {
    id: '6',
    title: 'Chocolate Chip Cookies',
    category: 'Dessert',
    area: 'American',
    instructions: 'Mix ingredients. Scoop onto baking sheet. Bake until golden brown.',
    tags: ['Dessert', 'Sweet', 'Baking'],
    imageUrl: 'https://www.themealdb.com/images/media/meals/1544384070.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=U9Y5Z6bX8q0',
    ingredients: [
      { ingredient: 'Flour', measure: '250g' },
      { ingredient: 'Sugar', measure: '150g' },
      { ingredient: 'Butter', measure: '100g' },
      { ingredient: 'Eggs', measure: '1' },
      { ingredient: 'Chocolate Chips', measure: '150g' },
      { ingredient: 'Baking Soda', measure: '1 tsp' },
      { ingredient: 'Salt', measure: 'a pinch' },
    ],
    dateModified: '2024-06-15',
  },
];
